### ISSUE TITLE
Username overflows profile box

### ISSUE THREAD

**Issue by joshvickerson** [MammothHQ/Known-Issues#14]
This happens when the window width is between 992px and 1199px (inclusive).

![screenshot 2013-10-10 09 03 15](https://f.cloud.github.com/assets/2325487/1306265/9a3ffbe4-31ac-11e3-9c89-fbc0e3d82521.png)

**Comment by karanmg** [comment]
Thanks, we'll be fixing this

**Comment by karanmg** [comment]
We've fixed this.
