### ISSUE TITLE
drop down covers first bookmark

### ISSUE THREAD

**Issue by jeffsteinmetz** [MammothHQ/Known-Issues#18]
when using mini mammoth (testing in Chrome), if you open a board, the first link is covered by the hover showing "drag anything in here or type below [Edit] [Share] [Fullscreen]".

Specifically - any time the mouse hovers in the link area, this pop up drops down, making it impossible to click the first link.

**Comment by karanmg** [comment]
Thanks for the feedback. Aware of this, understandably its annoying.
Will release a fix.
