### ISSUE TITLE
Text color not saved on board

### ISSUE THREAD

**Issue by coolv** [MammothHQ/Known-Issues#3]
I added a new board, dragged some pictures and added some text above the pictures.  When I selected the pictures and changed the font color I can see the font color changed.  But when I save my changes the font color reverts to black.  Other formatting, eg. paragraph format, bold, italic, all seem to be saved correctly. Any color formatting is stripped from the html.

Here is the html before the save ...
![HTMLBeforeSave](https://f.cloud.github.com/assets/2952764/357230/f8373db8-a122-11e2-92b8-7fe41630eaa5.PNG)

Here is the html after the save ...
![HTMLAfterSave](https://f.cloud.github.com/assets/2952764/357231/fbebb790-a122-11e2-965a-1b3d876811b8.PNG)

**Comment by karanmg** [comment]
Thanks for the info. 
We are aware of it, and its due to a little aggressive sanitization on our part. 
We'll be getting a fix out soon.

**Comment by karanmg** [comment]
We've pushed out a fix for this.
