### ISSUE TITLE
Deleted support board

### ISSUE THREAD

**Issue by mor10** [MammothHQ/Known-Issues#5]
According to the support page there is a support board added when your account is set up. Chances are people who like to start with a clean slate will delete this board not knowing what it is. There should be a) a flag on it saying "don't delete this" and b) some way to reinstate it. Or maybe there shouldn't be a support board at all?

**Comment by karanmg** [comment]
Support boards are used by many people, and keep track of feedback: so they serve a useful purpose.

The auto created support board is pre-populated with some text to indicate how it works. We could modify this text if its not indicative enough that the board shouldn't really be deleted.

To create a support board at any time, just create a new board and invite hello@mammothhq.com as an editor.

**Comment by mor10** [comment]
I understand the purpose of the board and it is a good idea. Maybe that last sentence should be added to the Support page?

**Comment by karanmg** [comment]
Thats a good suggestion. We'll add it.

**Comment by karanmg** [comment]
will be going live soon.
