### ISSUE TITLE
Sophos blocks Javascript

### ISSUE THREAD

**Issue by VolkerKaminDSA** [MammothHQ/Known-Issues#9]
*****************\* Sophos Anti-Virus Protokoll - 05.06.2013 08:41:33 **************

[...]
20130605 083813 Web-Anfrage an "js.pusher.com/1.12/pusher.min.js" (verlinkt von "mammothhq.com/boards") für Benutzer DOMAIN\user gesperrt. 'Troj/Redir-X' wurde auf dieser Website gefunden, Verweiskennung 146689853.
20130605 083946 Web-Anfrage an "js.pusher.com/1.12/pusher.min.js" (verlinkt von "mammothhq.com/boards") für Benutzer DOMAIN\user gesperrt. 'Troj/Redir-X' wurde auf dieser Website gefunden, Verweiskennung 146689853.
[...]

"DOMAIN\user" is a replacement for my real domain and user name.
This issue seems to be a heuristic acting up.

**Comment by karanmg** [comment]
Thanks for the specific info. Pusher has invited us to use the beta version of their latest lib, which is supposed to be immune to such av blocks. Will be looking into this.

For now, can you create a filter in Sophos to allow connections to pusher.com and pusherapp.com to go through?

**Comment by karanmg** [comment]
Mammoth now uses the latest version of the Pusher lib which is immune to such AV blocks. Let us know if you still see this problem.
